name: Build Redis:latest

on:
  push:
    branches:
      - "release-latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU # Build for more platforms
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: nguyenrazona/redis:latest
        # Github cache: comment out if error
        cache-from: type=gha
        cache-to: type=gha,mode=max
